name: excuserapp
description: A new Flutter project.
publish_to: "none"
version: 1.3.2+15

environment:
  sdk: ">=2.18.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0
  shimmer: ^3.0.0
  glass_kit: ^2.0.1
  google_mobile_ads: ^3.0.0
  webview_flutter: ^4.2.2
  supabase_flutter: ^1.10.10
  flutter_dotenv: ^5.1.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.10.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.3
  drift_db_viewer: ^2.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets\fonts\Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
  assets:
    - assets/fonts/
    - assets/icon/
    - .env
