name: excuserapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+8

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  drift_db_viewer: ^1.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  shimmer: ^2.0.0
  glass_kit: ^2.0.1
  envify: any
  google_mobile_ads: ^1.2.0
  webview_flutter: ^3.0.4
  devicelocale: ^0.5.2
  supabase_flutter: ^0.3.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.5.2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  icons_launcher: ^1.1.8
  envify_generator: any

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets\fonts\Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/images/